services:
  api:
    build: .
    container_name: securenotes-api
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/securenotes
      REDIS_URL: redis://redis:6379/0
      ENV: prod
      # JWT_SECRET: set this in a .env file (do not commit)
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
      
  db:
    image: postgres:16
    container_name: securenotes-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: securenotes
    ports:
      - "5432:5432"
    volumes:
      - secure-notes_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: securenotes-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - secure-notes_redisdata:/data

  caddy:
    image: caddy:2
    container_name: securenotes-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api

volumes:
  secure-notes_pgdata:
  secure-notes_redisdata:
  caddy_data:
  caddy_config:
